export const IMPORTANT_FILES = [
  "README.md",
  "package.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "package-lock.json",
  "requirements.txt",
  "pyproject.toml",
  "Pipfile",
  "poetry.lock",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  ".env.example",
  ".env.local.example",
  "next.config.js",
  "next.config.ts",
  "vite.config.ts",
  "vite.config.js",
  "prisma/schema.prisma",
  "manage.py",
  "app.py",
  "main.py",
  "go.mod",
  "Cargo.toml",
  "composer.json",
  "Gemfile",
] as const;

export type ImportantFilePath = (typeof IMPORTANT_FILES)[number];
